name: Update README

on:
  schedule:
    - cron: "4 * * * *"  # Москва = UTC+3
  workflow_dispatch: # Для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Обновлено с v2 на v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Обновлено с v2 на v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Run update_readme.py
      run: python update_readme.py

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "samhaev.e@yandex.ru"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Updated greeting"
        git push
